//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingAppTest.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        public decimal CustomerID { get; set; }
        public bool CustomerTitle { get; set; }
        public string CustomerFName { get; set; }
        public string CustomerLName { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string EmailAddress { get; set; }
    }
}
