//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingAppTest.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        public decimal ProductID { get; set; }
        public string ProductTitle { get; set; }
        public string ProductDescription { get; set; }
        public string ProductDescription2 { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Images { get; set; }
        public decimal Quantity { get; set; }
    }
}
